import { Metadata } from 'next';
import Link from 'next/link';
import Breadcrumbs from '@/components/Breadcrumbs';
import { ROUTES, SITE_HOST, SITE_NAME, SITE_ORIGIN, SUPPORT_EMAIL } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How alanodt5game.com.pk handles analytics, affiliate download clicks, and contact-form data for the Alano DT 5 guide.',
  alternates: { canonical: `${SITE_ORIGIN}${ROUTES.privacy}` },
};

export default function PrivacyPage() {
  return (
    <article className="max-w-4xl mx-auto px-4 py-12 prose-invert">
      <Breadcrumbs items={[{ name: 'Home', href: '/' }, { name: 'Privacy Policy', href: ROUTES.privacy }]} />
      <h1 className="text-4xl font-bold mb-6 text-white">Privacy Policy</h1>
      <p className="text-gray-400 mb-6">Last updated: 15 August 2026. Written for {SITE_HOST}, not generated by a policy wizard.</p>
      <div className="text-gray-300 space-y-4 leading-relaxed">
        <p>{SITE_NAME} on this domain is an informational APK guide. We do not operate the game wallet, store your JazzCash PIN, or see in-app balances.</p>
        <h2 className="text-2xl font-bold text-accent pt-4">Data we may collect</h2>
        <p>If Google Analytics is enabled via environment configuration, it records anonymised page views. The contact form stores the fields you type so we can reply. Download buttons send you to alanorunny.com; that site has its own policy.</p>
        <h2 className="text-2xl font-bold text-accent pt-4">Cookies</h2>
        <p>Essential cookies keep the site working. Analytics cookies load only when a measurement ID is configured.</p>
        <h2 className="text-2xl font-bold text-accent pt-4">Affiliate disclosure</h2>
        <p>The APK link includes referral code 14544841. We may receive a commission. That does not change the editorial warnings about loss and sideload risk.</p>
        <h2 className="text-2xl font-bold text-accent pt-4">Your requests</h2>
        <p>Email {SUPPORT_EMAIL} to ask for deletion of a contact-form message. Game account deletion must be requested from the publisher, not from us.</p>
        <p>Related: <Link href={ROUTES.disclaimer} className="text-accent hover:underline">Disclaimer</Link>.</p>
      </div>
    </article>
  );
}
